### ISSUE TITLE
write pitch to open austin

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/cultural-asset-mapping-project-old#3]
to see if we can get the map updating dynamically during the survey period

**Comment by Shirley-R** [comment]
### What problem are we trying to solve?

The City of Austin's Cultural Asset Mapping Project (CAMP) is looking for a way to collect crowdsourced responses to the question, "What are your district's cultural assets?" CAMP would like to create a map that not only dynamically updates with incoming responses, but also allows users to categorize, filter, and explore the map to see how organizations, businesses, and individuals coexist, cluster, and interact to form Austin's creative ecosystems.

### Who will benefit (directly and indirectly) from this project?

-City of Austin Departments and City Council: The data collected through the crowdsourced map can be used by multiple City departments and Council Members to help guide the development of creative economy and social well-being strategies and initiatives and better plan for Austin’s creative sector.

-Civic Hackers, App Developers, Cartographers, Artists, and Mapmakers of all kinds: The collected data will create a dataset we have yet to see here in Austin showcasing artist resources, venues, public art, creative studios, rehearsal spaces, and more. We will be sharing the data we collect through the Open Data Portal and can imagine creative apps/projects/initiatives that can take this dataset beyond the CAMP survey and crowdsourced map.

-Artists/Cultural Organizations/ Austinites thirsty for more culture:The CAMP map and the corresponding data can help Austin's creative sectors explore the resources available to them, discover new assets, and begin a dialogue about the needs of Austin's creative ecosystems. 

### Links to any research/data available/ articles

contact shirley.rempe@austintexas.gov for more info

### What are the next steps (validation, research, coding, design)?

-Coding: Develop a map that dynamically updates as survey respondents input addresses and/or crosstreets (would need to have a survey form that also geocodes…)

-Design: Spruce up the design of our github webpage to serve as fun and engaging tool to input responses (via some webform survey most likely), explore existing points, and learn more about the entire CAMP project.

### What help is needed at this time?

Design and coding help- CAMP could use the help of creative designers and coders to create a crowdsourced mapping tool that will be so fun to use that everyone will want to take part and submit their responses. We are also looking for designers willing to help us design our webpage to be engaging, a pleasure to use, and an exciting way to view and interact with the data we collect.

**Comment by Shirley-R** [comment]
Initial draft for dynamic web mapping and webpage design pitch to Open Austin

**Comment by haileypate** [comment]
@Shirley-R, your pitch is great! I've rearranged it just a tad and done some wordsmithing. If you think this will work for you, then it's time to post to Open Austin!

---

### What problem are we trying to solve?

The City of Austin needs more information to guide the development of creative economy and social well-being strategies and initiatives and better plan for Austin’s creative sector.

To this end, the City's Cultural Asset Mapping Project (CAMP) is looking for a way to collect and share crowdsourced responses to the question, "What are your district's cultural assets?" 

CAMP would like to create a map that not only dynamically updates with incoming responses, but also allows users to categorize, filter, and explore the map to explore how organizations, businesses, and individuals coexist, cluster, and interact to form Austin's creative ecosystems.

### Who will benefit (directly and indirectly) from this project?

**Civic Hackers, App Developers, Cartographers, Artists, and Mapmakers of all kinds:** The collected data will describe artist resources, venues, public art, creative studios, rehearsal spaces, and more. It will be published to the Open Data Portal within weeks of collection, making it freely available use in apps/projects/initiatives.

**Artists/Cultural Organizations/ Austinites thirsty for more culture:** The CAMP map and the corresponding data can help Austin's creative sectors explore the resources available to them, discover new assets, and begin a dialogue about the needs of Austin's creative ecosystems.

**City of Austin Departments and City Council:** To inform government activities and policy development related to Austin's creative sector.

### Links to any research/data available/articles

contact shirley.rempe@austintexas.gov for more info

Also, we've started a repo for this project here: https://github.com/cityofaustin/cultural-asset-mapping-project

### What are the next steps (validation, research, coding, design)?

We are ready for coders to pitch in!!!

See below for specifics. Fork at https://github.com/cityofaustin/cultural-asset-mapping-project

### What help is needed at this time?

**Project website:** Help is needed to spruce up the **design** of our github [webpage](http://cityofaustin.github.io/cultural-asset-mapping-project) to serve as a fun and engaging tool to input responses (via some webform survey most likely), explore existing points, and learn more about the entire CAMP project. We want it to be a pleasure to use, as well as an exciting way to view and interact with the data we collect. 

**Dynamic map:** We would love to feature a map on our [webpage](http://cityofaustin.github.io/cultural-asset-mapping-project) that dynamically updates as survey respondents submit new assets to the dataset. (City of Austin staff may need to review submissions first to ensure appropriateness or detect spam.)

**Comment by haileypate** [comment]
@Shirley-R, as we discussed in our meeting today, the plan for this project has changed. I'll update the readme.md file to reflect the new plan, and we'll postpone the pitch to Open Austin for August, after the data has been collected
